### ISSUE TITLE
Create script to import users from google form

### ISSUE THREAD

**Issue by asmahood** [uwpokerclub/tickets#164]
#### Description
At the first few events of the term, registering new members can be a long and tedious process, preventing us from starting the event when we would like. It would be great if we could fast track this system in some way. While we cannot yet just have a form on some public website due to security issues we would need to deal with, there is another possibility.

#### Solution
Google forms offer the availability to export the results as a spreadsheet, and hence can be exported as a CSV. We could write a script that reads this CSV, and for each row create a new user. This script will be easy enough for anyone with access to the Github repo to run before any event so the database is up to date.

The script should output some detailed information after the run is complete, with any users that failed to import output at the end. A failed user should not fail the entire script, instead just retaining the error information and continuing.

**Comment by fugitive-cat** [comment]
https://github.com/uwpokerclub/api/pull/154
